version: '3.8'
services:
  web:
    image: node:18
    container_name: serviciospsicologia-web
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && node server.js"
    ports:
      - "8021:8021"
    restart: unless-stopped
